# Generated by Django 5.2.5 on 2025-08-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.AddField(
            model_name='event',
            name='attendee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
