# Generated by Django 5.2.5 on 2025-08-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_event_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
